### ISSUE TITLE
Citing the package

### ISSUE THREAD

**Issue by kamalsaleh** [sunnyquiver/QPA2#41]
Hello, I'm wondering whether the following .bib entry is the correct way to cite the package:

```
@misc{ QPA2,
author =  {The QPA-team},
title =   {The {QPA2} package, A \textsf{GAP4} package for quivers, path algebras and representations, {V}ersion 2.0-dev},
year =    {2021},
note =    {(\url{https://www.math.ntnu.no/~oyvinso/QPA/})},
keywords =    {quiver; path algebra; quiver representations},
}

```

**Comment by sunnyquiver** [comment]
QPA2 is not so prominently mentioned on the web page https://www.math.ntnu.no/~oyvinso/QPA/, so that I think it is better if one would use  [https://github.com/sunnyquiver/QPA2](https://github.com/sunnyquiver/QPA2).  Otherwise it is all good.

@misc{ QPA2,
author =  {The QPA-team},
title =   {The {QPA2} package, A \textsf{GAP4} package for quivers, path algebras and representations, {V}ersion 2.0-dev},
year =    {2021},
note =    {(\url{https://github.com/sunnyquiver/QPA2})},
keywords =    {quiver; path algebra; quiver representations},
}

**Comment by kamalsaleh** [comment]
Thank you for the clarification.
